FROM scratch

# Jenkins home TODO move to /luci/jenkins_home
VOLUME /var/jenkins_home

# Artifactory
VOLUME /luci/artifactory/data
VOLUME /luci/artifactory/backup

# Gradle
VOLUME /luci/gradle/userhome

CMD not possible to run this container
